//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPersistence
{
    using System;
    
    public enum ContactGroup : int
    {
        Family = 0,
        Friends = 1,
        Coworkers = 2,
        None = 3,
        Other = 4
    }
}
