//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPersistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactEF
    {
        public ContactEF()
        {
            this.FirstName = "Not Set";
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public ContactGroup Group { get; set; }
        public string EmailAddressHome { get; set; }
        public string EmailAddressWork { get; set; }
        public string PhoneNumberHome { get; set; }
        public string PhoneNumberWork { get; set; }
    }
}
